INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (TRUE, 'admin', 'admin', 'admin@admin.com', 'admin', 25);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'Cubero Chico', '1234', 'luis@gmail.com', 'Luis', 26);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'Arjones', '1234', 'arjones@gmail.com', 'Antonio', 27);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'Martínez', '1234', 'juanC@gmail.com', 'Juan', 28);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'Gama', '1234', 'gabriel@gmail.com', 'Gabriel', 29);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'Campos', '1234', 'juan@gmail.com', 'Juan', 30);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'Romero', '1234', 'jose@gmail.com', 'Jose', 31);
INSERT INTO USUARIO (ADMIN, APELLIDOS, CONTRASENA, EMAIL, NOMBRE, ID) VALUES (FALSE, 'usuario', '1234', 'usuario@usuario', 'usuario', 32);

INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (300, 'Suite Oro', 31);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (200, 'Suite Oro', 32);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (100, 'Suite Oro', 34);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (400, 'Suite Oro', 35);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Oro', 36);

INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (300, 'Suite Diamante', 37);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (200, 'Suite Diamante', 38);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (100, 'Suite Diamante', 39);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (400, 'Suite Diamante', 40);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Diamante', 41);

INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Esmeralda', 46);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Esmeralda', 42);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Esmeralda', 43);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Esmeralda', 44);
INSERT INTO HABITACION (PRECIO, TIPOHAB, ID) VALUES (500, 'Suite Esmeralda', 45);